image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      curl -fsSL https://developer.modular.com/install | sh -
      echo 'export MODULAR_HOME="$HOME/.modular"' >> ~/.bashrc
      echo 'export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc
    command: |
      source ~/.bashrc
      mojo --version
