[workspace]
authors = ["Ruziboyev97 <97209027+Ruziboyev97@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.5.0,<26"
